---
environments:
  - label: '{python}-{cover}'
    matrix:
      python:
        $ref: '#/matrix/python'
      cover:
        $ref: '#/matrix/cover'
  - label: check-{python}
    matrix:
      python:
        $ref: '#/matrix/check-python'
    cover: false
    deps:
      - bandit
      - black
      - flake8
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
      - isort

matrix:
  check-python:
    - alias: py36
      value: "3.6"
    - alias: py37
      value: "3.7"
  python:
    - alias: py27
      value: "2.7"
    - alias: py34
      value: "3.4"
    - alias: py35
      value: "3.5"
    - alias: py36
      value: "3.6"
    - alias: py37
      value: "3.7"
  cover:
    - alias: cover
      value: true
    - alias: nocov
      value: false
  deps: []
  environment_variables: []

.travis.yml:
  secrets:
    codecov_token: "Gh2DOh4urKMY7fOiKCS6swICtNhMDkNS8N/Sdjtnip9IydkbJWDuW5ZbbdRXZPo/+gCXQqEov8HHoPduInjLUN5y0Idfm7G517FjnZa64nFw0PU9bwrAbvyjUqAcmj8yVOpEjPgxvIpccIujszldhm3Q9WXjh7B63hYAp45ZqDhbfrQGqSwuNMCuLLEJgzVeLsax2pS0TQhofHs8C/Jd/HRLIfLK4dwcb4kchE6hyuwllDXklOtNHXVFsTb1vp5CwX7N28i8IkAwbtwVCL6C6MsfvgKjxwZOAtSnPeqKaFPUwiMk1qgUNJGByxzJ2dD4sp8mBcNPYDPrqTsnR2+yeZxoc9h1k2JY0AZhdgY6c76e4zy+ZNMrd1hcIiCL8Lr0PEca9xwsfKJS5WGQ/axYWgddmZhoDlobgvQDNQTXyh+tNukKAlWl5LQdHWOKcejON62vYPSlWyaRBkDd9VjXd0YOv/y90X6/3TRF/bGzxYWFX/jNjaeOPtoiIPLkrGxzBvR2FknaVOfEZJyUtmCQ2JLr4NUZ1Fd4X6bZToL6EeLr2Igx+ehG7RKqu4X38fulsm19tsynSb+HP70W6yfq5cApsUXkdf8xK0uGpNwuSbqGPtCLvMUdp1N6wBiDn7agtYEqsgMyd+GQxa+8zKozP8URrrvqyCtwoB2O2R+rgMs="
    cc_test_reporter_id: "g07E8O0oYOqkdlogPUiJogl+eo2ebMykcXaZMgYQoKxhk8qhHEtTmnBQ63krZgbbFoyYorwo7QRX0pRRiqCpVbjFDEqUxUpGqiJjKIGAms59q8H6tHkGw/SBa3pvLGD64PDgOlrSVl5VFUP2josy1JbhFtpTSYm49gPYhCAE9pp5j+WqU0WapXiJFKC9Iqh0I75Sc+k6XOF/fBb7hV7WZz4oqXSP22yTufFuMQSNqUfAq63mld7H2hEOq438mbHMlNe8Ijia+g0RkgtMXAvD7ciSGEONC9FUa7bjW4ti46A/kJfpkHSvp5NCLg4WR/inQx8Sh1I93DbesqQWDX8+qiwpLUKXPgRNLUdq9bCPd2ogy1KJR/mtGav5TI6Fhb5Fu39p4Cr8cutL0+6YIs3YGfLZSAyJd5D/B3Os7ER3HkE14C9DH0jvEqFZsoKYAX5DCBiBoIjywHylq95WQIKfuyRQMt6hPEwYduxIgT8U1BC5IFSEd3XFauUBLpWrXQfTVsg9Tz/Uef4jl4y1AziJwGhAliGW64YxY4Md+4GniTWRU/8EQ0GciWV3cku9+AEwZ2y2bShr0bbxYduvBLQXYy3FDWopWKbpsI+NVm3mUgq8Pd87xg6FP161uEmz8opZc+QCx6vHAWUx3T70LI25Eg338zQ6fynT5QrAqXIwdHU="
    coveralls_repo_token: "eR4IV+Z95qvobFsCfqnsqe8v1eI7wnQH8VEqHv1vB5bAtmpo1X9IOhZsGL3jMYlD9THZgw1Fpr/X3FL3ckxEwjHNRf+qXNADwFjGwrT//5gvuelCvLANbGYIooavxTU/1OqYJN0GSYg9NyCO6GEToNOFkve4316XB1fT7ezSbyWWc/YV2oFE00YdqALafEhWl7DNQ8a77m5qgap041k0cP8c/d1RehsMzzHQ+rT286+WNDyI/mqIwCGIo0P3zb/TIElp7IMXCpy6tuWmihx3zLt/7sE3PrpCwfiPl/QUVVrHb9a2sD6uqaVm1IXXmwVI+jVhpoPMPfEx4AZfErcF+J5yFnHCQLf3QErP+uqn2WwkoVAeVdvxy7/jBqDuQA1y0DvTRkrdZEFnUB+1WL5c1fCjeOFQXRQaG176pVkQGVzSTDd06tjoiRpqznUjxhczo/9InZawX++4cVRRpSYX+yXIMPk6xy3ivuy2djJC5DTgKCfAYT6biTi8ZuuJd/UtGvpPglSlRgwFxN7juhsw3xygSpwvpVbMpmKSfv07L2jJQTBnTZy+YdJS2/yFIZvlepYNsumSQ0C4gsHmYvL8z7OG/ARXOG0TptJzHr3J6qcyeq83MF9YKIWqIxMw9/gg81bo20c16CIehQ4Tzg14CezSfV2HKRUyfUO42FnI6vM="
    pypy_password: "M8hXlxRBnTjnBib4n2Tkua2gpA2tNdCeVnzrUG/1NvnGj0Tv+6JU4H3Kop0Ewzzkwp+ah/zuFpAmlORmvkmbDRc2fFzbrGS8ah4/ChqFQLbiIxSgX/84FR9ytS4HxVtatVGyTHwGoQC4x0l0ICsDBwK23arMwfgGJ2gxRpzdQ+Fx00qInKUYc7J83C+D/gP9wWwzhTi/RXwe8zVGcGnlJongIOGHjTKNIREx0hvEAJ2DEbelYYNc4STKLPZ43kfPDyMXi972o+dWfhqSXRpSFOGhOCcimcvKrvbIHt3xDO2X9+O28A9rgUq7gKjG6z8ziaBKW+3/oIvYlH96vzu0AAOHpBTcD0y9CAdPBs+Xtl8B977u+FVVCRseEl56q7mzNqsh0k7Pd7R4Rgcab/+J60H/IQ252uyaGBF0RJX1BOvizCS2y7/zuTe6srzk8jHzafWGa/4E4EaHrf62UUKKji/LDm6wF570kpBQi5KzCPLFbvYK6xpilAowXhoYA8cmVTXlCiGd5SW9YKGP68AHpFhHR3RAYmZq+IV/8M3FlwLMJKxhq+DIszBiC8aiSBpICHiaCv4H4eCjU6n13LIh9XSkNM5Lj9UydpM5idsKgx/tZfyWy2MR+y+XaIEatwNDNdQK3ro7CzE7inhsKEEZIJL5FTBJxcWXbrGh/sWWwjE="
