language: python
sudo: false
cache: pip

env:
  global:
    LD_PRELOAD: /lib/x86_64-linux-gnu/libSegFault.so
    SEGFAULT_SIGNALS: all
    CODECOV_TOKEN:
      secure: Gh2DOh4urKMY7fOiKCS6swICtNhMDkNS8N/Sdjtnip9IydkbJWDuW5ZbbdRXZPo/+gCXQqEov8HHoPduInjLUN5y0Idfm7G517FjnZa64nFw0PU9bwrAbvyjUqAcmj8yVOpEjPgxvIpccIujszldhm3Q9WXjh7B63hYAp45ZqDhbfrQGqSwuNMCuLLEJgzVeLsax2pS0TQhofHs8C/Jd/HRLIfLK4dwcb4kchE6hyuwllDXklOtNHXVFsTb1vp5CwX7N28i8IkAwbtwVCL6C6MsfvgKjxwZOAtSnPeqKaFPUwiMk1qgUNJGByxzJ2dD4sp8mBcNPYDPrqTsnR2+yeZxoc9h1k2JY0AZhdgY6c76e4zy+ZNMrd1hcIiCL8Lr0PEca9xwsfKJS5WGQ/axYWgddmZhoDlobgvQDNQTXyh+tNukKAlWl5LQdHWOKcejON62vYPSlWyaRBkDd9VjXd0YOv/y90X6/3TRF/bGzxYWFX/jNjaeOPtoiIPLkrGxzBvR2FknaVOfEZJyUtmCQ2JLr4NUZ1Fd4X6bZToL6EeLr2Igx+ehG7RKqu4X38fulsm19tsynSb+HP70W6yfq5cApsUXkdf8xK0uGpNwuSbqGPtCLvMUdp1N6wBiDn7agtYEqsgMyd+GQxa+8zKozP8URrrvqyCtwoB2O2R+rgMs=
    CC_TEST_REPORTER_ID:
      secure: g07E8O0oYOqkdlogPUiJogl+eo2ebMykcXaZMgYQoKxhk8qhHEtTmnBQ63krZgbbFoyYorwo7QRX0pRRiqCpVbjFDEqUxUpGqiJjKIGAms59q8H6tHkGw/SBa3pvLGD64PDgOlrSVl5VFUP2josy1JbhFtpTSYm49gPYhCAE9pp5j+WqU0WapXiJFKC9Iqh0I75Sc+k6XOF/fBb7hV7WZz4oqXSP22yTufFuMQSNqUfAq63mld7H2hEOq438mbHMlNe8Ijia+g0RkgtMXAvD7ciSGEONC9FUa7bjW4ti46A/kJfpkHSvp5NCLg4WR/inQx8Sh1I93DbesqQWDX8+qiwpLUKXPgRNLUdq9bCPd2ogy1KJR/mtGav5TI6Fhb5Fu39p4Cr8cutL0+6YIs3YGfLZSAyJd5D/B3Os7ER3HkE14C9DH0jvEqFZsoKYAX5DCBiBoIjywHylq95WQIKfuyRQMt6hPEwYduxIgT8U1BC5IFSEd3XFauUBLpWrXQfTVsg9Tz/Uef4jl4y1AziJwGhAliGW64YxY4Md+4GniTWRU/8EQ0GciWV3cku9+AEwZ2y2bShr0bbxYduvBLQXYy3FDWopWKbpsI+NVm3mUgq8Pd87xg6FP161uEmz8opZc+QCx6vHAWUx3T70LI25Eg338zQ6fynT5QrAqXIwdHU=
    COVERALLS_REPO_TOKEN:
      secure: eR4IV+Z95qvobFsCfqnsqe8v1eI7wnQH8VEqHv1vB5bAtmpo1X9IOhZsGL3jMYlD9THZgw1Fpr/X3FL3ckxEwjHNRf+qXNADwFjGwrT//5gvuelCvLANbGYIooavxTU/1OqYJN0GSYg9NyCO6GEToNOFkve4316XB1fT7ezSbyWWc/YV2oFE00YdqALafEhWl7DNQ8a77m5qgap041k0cP8c/d1RehsMzzHQ+rT286+WNDyI/mqIwCGIo0P3zb/TIElp7IMXCpy6tuWmihx3zLt/7sE3PrpCwfiPl/QUVVrHb9a2sD6uqaVm1IXXmwVI+jVhpoPMPfEx4AZfErcF+J5yFnHCQLf3QErP+uqn2WwkoVAeVdvxy7/jBqDuQA1y0DvTRkrdZEFnUB+1WL5c1fCjeOFQXRQaG176pVkQGVzSTDd06tjoiRpqznUjxhczo/9InZawX++4cVRRpSYX+yXIMPk6xy3ivuy2djJC5DTgKCfAYT6biTi8ZuuJd/UtGvpPglSlRgwFxN7juhsw3xygSpwvpVbMpmKSfv07L2jJQTBnTZy+YdJS2/yFIZvlepYNsumSQ0C4gsHmYvL8z7OG/ARXOG0TptJzHr3J6qcyeq83MF9YKIWqIxMw9/gg81bo20c16CIehQ4Tzg14CezSfV2HKRUyfUO42FnI6vM=

matrix:
  include:
    - python: "3.6"
      env:
        - TOXENV=check-py36
    - python: "3.7"
      dist: xenial
      sudo: required
      env:
        - TOXENV=check-py37
    - python: "2.7"
      env:
        - TOXENV=py27-nocov
    - python: "3.4"
      env:
        - TOXENV=py34-nocov
    - python: "3.5"
      env:
        - TOXENV=py35-nocov
    - python: "3.6"
      env:
        - TOXENV=py36-nocov
    - python: "3.7"
      dist: xenial
      sudo: required
      env:
        - TOXENV=py37-nocov
    - python: "2.7"
      env:
        - TOXENV=py27-cover,report,coveralls,codecov,ocular
    - python: "3.4"
      env:
        - TOXENV=py34-cover,report,coveralls,codecov,ocular
    - python: "3.5"
      env:
        - TOXENV=py35-cover,report,coveralls,codecov,ocular
    - python: "3.6"
      env:
        - TOXENV=py36-cover,report,coveralls,codecov,ocular
    - python: "3.7"
      dist: xenial
      sudo: required
      env:
        - TOXENV=py37-cover,report,coveralls,codecov,ocular

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - |
    set -ex
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then
      (cd $HOME
       wget https://bitbucket.org/pypy/pypy/downloads/pypy2-v6.0.0-linux64.tar.bz2
       tar xf pypy2-*.tar.bz2
       pypy2-*/bin/pypy -m ensurepip
       pypy2-*/bin/pypy -m pip install -U virtualenv)
      export PATH=$(echo $HOME/pypy2-*/bin):$PATH
      export TOXPYTHON=$(echo $HOME/pypy2-*/bin/pypy)
    fi
    if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then
      (cd $HOME
       wget https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux64.tar.bz2
       tar xf pypy3-*.tar.bz2
       pypy3-*/bin/pypy3 -m ensurepip
       pypy3-*/bin/pypy3 -m pip install -U virtualenv)
      export PATH=$(echo $HOME/pypy3-*/bin):$PATH
      export TOXPYTHON=$(echo $HOME/pypy3-*/bin/pypy3)
    fi
    set +x
  - pip install -U tox pbr
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - tox -v

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || true

deploy:
  provider: pypi
  user: demosdemon
  distributions: "sdist bdist_wheel"
  skip_existing: true
  password:
    secure: M8hXlxRBnTjnBib4n2Tkua2gpA2tNdCeVnzrUG/1NvnGj0Tv+6JU4H3Kop0Ewzzkwp+ah/zuFpAmlORmvkmbDRc2fFzbrGS8ah4/ChqFQLbiIxSgX/84FR9ytS4HxVtatVGyTHwGoQC4x0l0ICsDBwK23arMwfgGJ2gxRpzdQ+Fx00qInKUYc7J83C+D/gP9wWwzhTi/RXwe8zVGcGnlJongIOGHjTKNIREx0hvEAJ2DEbelYYNc4STKLPZ43kfPDyMXi972o+dWfhqSXRpSFOGhOCcimcvKrvbIHt3xDO2X9+O28A9rgUq7gKjG6z8ziaBKW+3/oIvYlH96vzu0AAOHpBTcD0y9CAdPBs+Xtl8B977u+FVVCRseEl56q7mzNqsh0k7Pd7R4Rgcab/+J60H/IQ252uyaGBF0RJX1BOvizCS2y7/zuTe6srzk8jHzafWGa/4E4EaHrf62UUKKji/LDm6wF570kpBQi5KzCPLFbvYK6xpilAowXhoYA8cmVTXlCiGd5SW9YKGP68AHpFhHR3RAYmZq+IV/8M3FlwLMJKxhq+DIszBiC8aiSBpICHiaCv4H4eCjU6n13LIh9XSkNM5Lj9UydpM5idsKgx/tZfyWy2MR+y+XaIEatwNDNdQK3ro7CzE7inhsKEEZIJL5FTBJxcWXbrGh/sWWwjE=
  on:
    tags: true
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
